### ISSUE TITLE
Configurar TravisCI para desconsiderar branchs diferentes de jekyll no scritp de deploy

### ISSUE THREAD

**Issue by rtancman** [pythonbnu/pythonbnu.github.io#8]
Atualmente ao abri um PR no site o processo de build executa o script de deploy quebrando o PR.

**Comment by jjpaulo2** [comment]
@rtancman esse problema ainda existe?

Encontrei isso no `deploy.yaml`

```yaml
on:
  push:
    branches:
      - jekyll
```
